# Generated by Django 5.0.3 on 2024-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
